### ISSUE TITLE
params.pp breaks on puppet 4.

### ISSUE THREAD

**Issue by senax** [bodgit/puppet-rngd#2]
Hi,

in Puppet 4 the cases need some quotes to turn them to strings to prevent these:

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, The rngd module is not support on an RedHat 7 based system. at /etc/puppetlabs/code/environments/../modules/external/rngd/manifests/params.pp:17:11`

This fixed it for me:

>   case $::operatingsystemmajrelease {
>      '5': {..}
>      '6', '7': {..}

Thanks,
Frank

**Comment by bodgit** [comment]
Sorry, completely forgot about this. I've made this change and should appear as v1.0.1 on the forge shortly.

Thanks for the bug report, I suspect I'll need to make a similar change to my other modules.
