### ISSUE TITLE
adding extra-opts for systems without /dev/tpm0

### ISSUE THREAD

**Issue by nomoresecrets** [bodgit/puppet-rngd#3]
Would you mind adding a parameter to specify extra opts in file /etc/sysconfig/rngd?

On my virtual machines I'd have to specify another device than /dev/tpm0

**Comment by bodgit** [comment]
Is it the `-r/--rng-device=file` option that you need exposing?

**Comment by nomoresecrets** [comment]
yep it's that option :)

**Comment by bodgit** [comment]
I've added a `hwrng_device` parameter which allows you to specify the argument to `-r`. I found a minor bug on RHEL/CentOS 7 where the `/etc/sysconfig/rngd` file exists but it doesn't actually get read by the systemd unit so there's some extra configuration to make that work.

**Comment by bodgit** [comment]
It should be up on the forge released as v1.1.0.
